site_name: Rage.
site_url: https://12age.github.io/mymkdocs/
site_author: Rage.

# 主题配置
theme:
  logo: assets/雪乃logo.png
  name: material  # 主题名称
  favicon: images/雪乃.png
  custom_dir: overrides
  palette:
    # 白天/黑夜切换配置（列表项，属于 palette 的子项）
    - scheme: default  # 浅色模式
      #primary: yellow  # 主色调（正确缩进：比 palette 多 2 空格）
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate    # 深色模式
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: custom # 请求更改主色调
  features:
    - navigation.tabs #启用标签栏
    - navigation.tabs.sticky #启用标签栏的粘性
    - navigation.tracking #启用页面跟踪 复制当前页面 URL，就能精确定位到当前段落，方便分享与回访
    - navigation.sections #启用页面标题
    - navigation.path #启用页面路径
    - navigation.expand #让左侧的文档目录在页面加载时自动展开所有层级
    - navigation.indexes #将文档直接附加到节
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - content.code.copy #代码复制
    - content.action.view #在页面内容区域显示“查看源码”按钮
    - content.code.annotate
    - navigation.footer # 添加页脚 上一页 下一页
    #- navigation.instant #XHR调度 会有bug 首页的背景到其他页也显示
    #- navigation.instant.progress #XHR加载进度条
    #- toc.integrate #侧边目录展开并跟随 有bug会导致首页偏右
  language: zh # 一些提示性的文字会变成中文

extra:
  generator: false #是否删除页脚显示“使用 MkDocs 构建”
  social:
    # - icon: fontawesome/brands/weixin
    #   link: #https://s1.imagehub.cc/images/2024/02/02/bb9ee71b03ee7a3b87caad5cc4bcebff.jpeg
    - icon: fontawesome/brands/github
      link: https://github.com/12age
      name: GitHub
copyright: Copyright &copy; 2022-2025 Rage. # 左下角的版权声明
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称


extra_css:
  - stylesheets/extra.css # 自定义的CSS
  - https://static.zeoseven.com/zsft/292/main/result.css #引入字体

extra_javascript:
  - javascripts/extra.js #自定义的javascript

nav:
  - 每日面试题:
    - 每日面试题目录: blog/每日面试题/每日面试题目录.md
    - 2025年8月29日: blog/每日面试题/2025年8月29日.md
    - 2025年8月27日: blog/每日面试题/2025年8月27日.md
    - 2025年8月23日: blog/每日面试题/2025年8月23日.md
    - 2025年8月22日: blog/每日面试题/2025年8月22日.md
    - 2025年8月19日: blog/每日面试题/2025年8月19日.md
  - 项目技术点总结:
    - Tlias智能辅助学习系统技术点总结: blog/项目总结/Tlias智能辅助学习系统技术点总结.md
  - 易错易忘易混淆总结:
    - 全局异常处理: blog/易错易忘易混淆总结/全局异常处理.md
    - 判断查询返回的结果集合null和空: blog/易错易忘易混淆总结/判断查询返回的结果集合null和空.md
    - 三层架构用到的注解总结: blog/易错易忘易混淆总结/三层架构用到的注解总结.md
    - Path多个变量: blog/易错易忘易混淆总结/Path多个变量.md
    - 动态 SQL 的使用时机: blog/易错易忘易混淆总结/动态 SQL 的使用时机.md
    - 多个参数接收总结: blog/易错易忘易混淆总结/多个参数接收总结.md
    - Controller与Mapper接收参数: blog/易错易忘易混淆总结/Controller与Mapper接收参数.md
    - MyBatis同名表不同库: blog/易错易忘易混淆总结/[MyBatis]同名表不同库.md
    - MyBatis + PageHelper 实现分页: blog/易错易忘易混淆总结/MyBatis + PageHelper 实现分页.md
    - Mybatis @Param: blog/易错易忘易混淆总结/Mybatis @Param.md
    - MyBatis 动态 SQL: blog/易错易忘易混淆总结/MyBatis 动态 SQL.md
    - 事务@Transactional(rollbackFor = Exception.class)和事务传播: blog/易错易忘易混淆总结/事务@Transactional(rollbackFor = Exception.class)和事务传播.md


  - 前端:
    - HTML&CSS: blog/前端/HTML&CSS.md


